# Generated by Django 5.2.8 on 2025-11-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_worktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_workertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workertype_name', models.CharField(max_length=50)),
            ],
        ),
    ]
