# Generated by Django 5.2.8 on 2025-12-06 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Builder', '0009_remove_tbl_assign_assign_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updates_content', models.CharField(max_length=50)),
                ('updates_date', models.DateField(auto_now_add=True)),
                ('updates_status', models.IntegerField(default=0)),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Builder.tbl_assign')),
            ],
        ),
    ]
