# Generated by Django 5.2.8 on 2025-11-29 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0007_tbl_workertype'),
        ('Guest', '0003_alter_tbl_builders_builders_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=50)),
                ('worker_email', models.CharField(max_length=50)),
                ('worker_contact', models.CharField(max_length=50)),
                ('worker_photo', models.FileField(upload_to='Assets/WorkerDocs/')),
                ('worker_password', models.CharField(max_length=50)),
                ('worker_status', models.CharField(max_length=50)),
                ('builder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_builders')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('workertype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_workertype')),
            ],
        ),
    ]
