# Generated by Django 5.2.8 on 2025-11-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Builder', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_worker',
        ),
    ]
