# Generated by Django 5.2.8 on 2025-11-29 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Builder', '0005_initial'),
        ('Guest', '0003_alter_tbl_builders_builders_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=50)),
                ('work_details', models.CharField(max_length=50)),
                ('work_photo', models.FileField(upload_to='Assets/WorkDocs/')),
                ('work_date', models.DateField(auto_now_add=True)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_builders')),
            ],
        ),
    ]
