# Generated by Django 5.2.8 on 2025-12-04 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Builder', '0006_tbl_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_workgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_file', models.CharField(max_length=50)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Builder.tbl_work')),
            ],
        ),
    ]
