# Generated by Django 5.2.8 on 2025-12-05 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Builder', '0007_tbl_workgallery'),
        ('User', '0004_rename_reuest_file_tbl_request_request_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_content', models.CharField(max_length=50)),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('assign_status', models.IntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_request')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Builder.tbl_worker')),
            ],
        ),
    ]
