# Generated by Django 5.2.8 on 2025-12-06 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Builder', '0008_tbl_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_assign',
            name='assign_content',
        ),
    ]
