# Generated by Django 5.2.8 on 2025-12-12 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Builder', '0009_remove_tbl_assign_assign_content'),
        ('Guest', '0003_alter_tbl_builders_builders_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.CharField(max_length=50)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_builders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Builder.tbl_worker')),
            ],
        ),
    ]
