# Generated by Django 5.2.8 on 2025-12-12 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Builder', '0010_tbl_feedback'),
        ('Guest', '0003_alter_tbl_builders_builders_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_feedback',
            name='builder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_builders'),
        ),
        migrations.AlterField(
            model_name='tbl_feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
        migrations.AlterField(
            model_name='tbl_feedback',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Builder.tbl_worker'),
        ),
    ]
