# Generated by Django 5.2.8 on 2025-11-28 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_workertype'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_dob',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='tbl_builders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builders_name', models.CharField(max_length=50)),
                ('builders_email', models.CharField(max_length=50)),
                ('builders_contact', models.CharField(max_length=50)),
                ('builders_address', models.CharField(max_length=50)),
                ('builders_logo', models.FileField(upload_to='Assets/BuilderDocs/')),
                ('builders_license', models.CharField(max_length=50)),
                ('builders_status', models.CharField(max_length=50)),
                ('builders_password', models.CharField(max_length=50)),
                ('builders_doj', models.DateField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
