# Generated by Django 5.2.8 on 2025-11-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_alter_tbl_user_user_dob_tbl_builders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_builders',
            name='builders_license',
            field=models.FileField(upload_to='Assets/BuilderDocs/'),
        ),
    ]
