# Generated by Django 5.2.8 on 2026-01-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_remove_tbl_user_user_dob_remove_tbl_user_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_builders',
            name='builders_status',
            field=models.IntegerField(default=0),
        ),
    ]
