# Generated by Django 5.2.8 on 2025-12-04 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_alter_tbl_builders_builders_license'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reuest_file', models.FileField(upload_to='Assets/requestDocs/')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=0)),
                ('request_amount', models.CharField(max_length=50)),
                ('request_content', models.CharField(max_length=50)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_builders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
