# Generated by Django 5.2.8 on 2025-12-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_request',
            name='request_amount',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
