# Generated by Django 5.2.8 on 2025-12-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_tbl_request_request_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_request',
            old_name='reuest_file',
            new_name='request_file',
        ),
    ]
